name: CI

on:
  push:
    branches: [ main, master, prod ]
  pull_request:
    branches: [ main, master, prod ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npm run prisma:generate:test
      env:
        DATABASE_URL: postgresql://postgres:docker@localhost:5432/projectdb?schema=test

    - name: Run Prisma Migrations
      run: npm run prisma:migrate:test
      env:
        DATABASE_URL: postgresql://postgres:docker@localhost:5432/projectdb?schema=test

    - name: Run tests
      run: npm run test:unit
      env:
        DATABASE_URL: postgresql://postgres:docker@localhost:5432/projectdb?schema=test